### ISSUE TITLE
problem with the binary

### ISSUE THREAD

**Issue by jkozniewski** [andrewheumann/jSwan#3]
Under Rhino5 on Windows there is and error displayed when Grashopper is loading stating that the binary has been built against different version of SDK - see the screenshoot below:
![Screenshot 2020-02-14 12 59 56](https://user-images.githubusercontent.com/6979983/74530795-3d5e4e00-4f2b-11ea-84df-a4be48123065.jpg)

**Comment by andrewheumann** [comment]
Rhino 5 is not supported
