### ISSUE TITLE
ERROR MESSAGE: The jSwan component library was built against a newer minor version of the Grasshopper SDK

### ISSUE THREAD

**Issue by nicolajlangkjaer** [andrewheumann/jSwan#7]
Hi,

When i try to load the jSwan component onto the grasshopper canvas i get an error message saying: "the jSwan component library was built against a newer minor version of the Grasshopper SDK"

I am running Rhino 6 on a PC.

I hope you can help me here.

**Comment by andrewheumann** [comment]
This is resolved by updating Rhino 6 to the latest service release.
