### ISSUE TITLE
Error Message in Rhino Console: The file or assembly "file:///C:\Users\vnk\AppData\Roaming\Grasshopper\Libraries\jswan.gha" or a dependency on it was not found. The operation is not supported. (HRESULT exception: 0x80131515)

### ISSUE THREAD

**Issue by tommyvenek** [andrewheumann/jSwan#8]
jSwan Plug-In is not appering in Grasshopper

**Comment by kenjiiimura** [comment]
Hi tommy,
I joined to GitHub today and I saw your post.
This issue happens to me too.
You can solve this problem by following step.

- Go to %AppData%\\Roaming\Grasshopper\Libraries 
- Right click jswan.gha
- I think you can see some option about block or release at bottom of the window.
- Release it
- Then start Rhino & Grashopper!

I hope this help you. (Although 4 month passed from your post....)

**Comment by andrewheumann** [comment]
Yes @kenjiiimura is correct: be sure to right click the GHA and unblock.
