### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.

### ISSUE THREAD

**Issue by nordbim** [andrewheumann/jSwan#9]
Hi, 
I am getting this error when trying to load the jswan_0.gha in Grasshopper 7. 

An error occured during GHA assembly loading:
  Path: C:\Users\samue\AppData\Roaming\Grasshopper\Libraries\jswan_0.gha
  Exception System.IO.FileNotFoundException: 
  Message: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by garciadelcastillo** [comment]
This can be solved by downloading `Newtonsoft.Json.dll` from [here](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/12.0.2) and placing the file right next to your `jSwan.gha` in your GH libraries folder (don't forget to unblock it).

**Comment by Tokarzewski** [comment]
@garciadelcastillo I can't find dll in your link. Can you help me?

**Comment by max-malein** [comment]
It would be nide to include Newtonsoft.Json.dll in the package.

**Comment by andrewheumann** [comment]
Apologies, never realized that newtonsoft wasn't included since so many other plugins package it, so it never caused an issue for me. Will package it with the next release.

**Comment by max-hans** [comment]
I case someone is wondering, the file is `Bin/net45/Newtonsoft.Json.dll`
